name: parametric_model_hw
channels:
- nvidia
- pytorch
- iopath
- bottler
- pytorch3d
- conda-forge  # Should be the last https://stackoverflow.com/a/69180871
dependencies:
- python>=3.9
- pip
- jupyterlab>=3.0
- jupyter
- ipykernel
- jupyter-lsp
- jupyterlab-lsp
- python-language-server
- jedi=0.17.2 # pinned because one of the language server packages needs it precisely pinned here
- torchvision
- pytorch-cuda==11.6
- pytorch3d
- pytorch==1.13.0
- cudatoolkit==11.8
- nvidiacub
- pip:
  - opencv-python
  - tqdm
  - matplotlib
  - scikit-image
  - plotly
  - kornia
  - imageio
  - chumpy
#  - mxnet-mkl==1.6.0  # TODO: validate if these are required.
  - numpy==1.23.1
  - face_alignment
  - moviepy